spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pesticide
    username: root
    password: 123456
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

mybatis:
  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.wjy.pesticide.model  # 注意：对应实体类的路径

